version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-secauto
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  secauto:
    build: .
    container_name: secauto-server
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - ../automations:/app/automations:ro
      - ../playbooks:/app/playbooks:ro
      - ../Venv:/app/Venv:ro
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: ["./secauto.exe"]

volumes:
  redis_data: 